feat/25 navbar component
qiskit-community/qiskit-vue pull request #28
Opened 2021-10-06 12:12 UTC by eddybrando

This PR creates a reusable **Navbar** component.

---

Closes https://github.com/qiskit-community/qiskit-vue/issues/25 and https://github.com/Qiskit/qiskit.org/issues/2173

2021-10-06 14:51 UTC, abdonrd reviewed
Why SVG logo and icons as components and not as `.svg` files?

2021-10-06 14:51 UTC, abdonrd commented on src/components/navbar/Navbar.vue
> +      </footer>
Couldn't the footer be undocked from the navbar? Thoughts?

2021-10-06 14:53 UTC, eddybrando commented on .storybook/preview.js
> +import "carbon-web-components/es/components/dropdown";
It caused issues with Nuxt's SSR on qiskit.org that broke the page.

2021-10-06 14:55 UTC, eddybrando commented on src/components/navbar/Navbar.vue
> +      </footer>
Just in case, this is not the _page's footer_, but the footer that appears in the navbar in small screens.

2021-10-06 14:57 UTC, eddybrando commented on .storybook/preview.js
> +import "carbon-web-components/es/components/dropdown";
There was a similar issue with SVG images on Platypus. They didn't want to load.

This might be related to the way we currently ship the components (without compiling / packaging the components / assets). Once Nuxt 3 is available and we can drop support for Vue 2, I think that we can start to ship the components properly as intended by `vue-cli`. And I hope to then be able to replaces the SVG components with proper SVG files.

2021-10-06 19:13 UTC, eddybrando commented on .storybook/preview.js
> +import "carbon-web-components/es/components/dropdown";
Exactly, so we need to also include the web component in the project that uses the Navbar.

This is hopefully only a provisory solution until we can properly package components after Nuxt 3 is available.

2021-10-07 09:17 UTC, korgan00 requested changes

2021-10-07 11:47 UTC, abdonrd approved these changes

2021-10-07 12:36 UTC, korgan00 approved these changes

2021-10-07 12:51 UTC, merged